version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: softwood-lumber-app
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # Uncomment and set these values before running, or use a .env file
      #- LLAMA_CLOUD_API_KEY=your_key_here
      #- GEMINI_API_KEY=your_key_here
      #- OPENAI_API_KEY=your_key_here
    volumes:
      # Mount .env file for API keys
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Limit resources to prevent container from consuming too much
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
