version: '3.8'

services:
  softwood-lumber:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    container_name: softwood-lumber
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS=ignore
    # Make the container start automatically in the background
    # Remove this if you want to see the logs directly in the console
    # detach: true
